http:
    middleware:
        - CORSGinHTTPMiddleware
        - RequestChainHTTPMiddleware
    # middleware:
        # - Logger
        # - CORS
        # - Recovery
        # - CaughtError
        # - Sentry
        # - Swagger
        # - RequestID
        # - Sentry

    static:
        - public

redis:
    default:
        password: ""
        host: 127.0.0.1
        port: 6379
        name: 0