application:
    enviroment: local
    debug: true

http:
    middleware:
        - CORSGinHTTPMiddleware
        - RequestChainHTTPMiddleware
    # middleware:
        # - Logger
        # - CORS
        # - Recovery
        # - CaughtError
        # - Sentry
        # - Swagger
        # - RequestID
        # - Sentry

    static:
        - public

    server:
        port: 4070
        timeout:
            read: 10000
            write: 10000

logger:
    handlers:
        graylog:
            host: 127.0.0.1
            port: 0000
            protocol: udp
            level: DEBUG

        console:
            level: DEBUG

database:
    default:
        host: 127.0.0.1
        port: 3306
        username: root
        password: ""
        database: example
        max_idle: 10
        max_open: 200
        max_left_time: 3600
        # prefix: 
        log_sql: true
        log_sql_execute_time: true
        log_level: INFO
redis:
    default:
        password: ""
        host: 127.0.0.1
        port: 6379
        name: 0