application:
    enviroment: local
    debug: true
consul: 
    url: consul.gaodunwangxiao.com
    list_name: gaodun/config_center/
    env_fix: 
        local: test.
        test: t.
        prepare: pre.
        production : pro.
http:
    middleware:
        - CORSGinHTTPMiddleware
        - RequestChainHTTPMiddleware
       - SessionsGinHTTPMiddleware
    # middleware:
        # - Logger
        # - CORS
        # - Recovery
        # - CaughtError
        # - Sentry
        # - Swagger
        # - RequestID
        # - Sentry

    static:
        - public

    server:
        port: 4070
        timeout:
            read: 60
            write: 60

logger:
    handlers:
        graylog:
            host: g02.graylog.gaodunwangxiao.com
            port: 5504
            protocol: udp
            level: -1
        console:
            level: DEBUG
    fields: item:testnow

database:
    default:
        type: mysql
        host: localhost
        port: 3306
        username: root
        password: "123456"
        database: test
        max_idle: 10
        max_open: 200
        max_left_time: 3600
        # prefix: 
        log_sql: true
        log_sql_execute_time: true
        log_level: INFO
redis:
    default:
        password: ""
        host: 127.0.0.1
        port: 6379
        name: 0